### ISSUE TITLE
Tool sidebar is not populated

### ISSUE THREAD

**Issue by Yeeshani** [dolfinus/DarkVector#20]
The heading is there but no entries are generated. It works with the default Vector skin.

**Comment by Yeeshani** [comment]
Changing [this line](https://github.com/dolfinus/DarkVector/blob/master/DarkVectorTemplate.php#L274) to

```php 
$this->renderPortal( 'tb', $this->getToolbox(), 'toolbox', 'SkinTemplateToolboxEnd' );
```

worked for me. Not sure if it is a good solution.

**Comment by dolfinus** [comment]
Hello.

What MediaWiki version do you use?

MediaWiki 1.36 marked some functions like `getToolbox` as deprecated:
https://github.com/dolfinus/DarkVector/pull/13#issuecomment-723594216

That's why I've changed this like:
https://github.com/dolfinus/DarkVector/pull/13/files#diff-e39200ff4300e4bbc598a529ce6e5e06b4d5759e9e4455d80c7ce3671992c1bbL274

**Comment by Yeeshani** [comment]
Oh. I'm still on 1.34. Which does not seem to fill data['sidebar']['TOOLBOX']. It's there, but empty.

Anyway that cleans up the problem. Thanks for looking into it.

**Comment by dolfinus** [comment]
Could you check is the `mw-1.31` branch working properly, please?

**Comment by Yeeshani** [comment]
It seems to be working. I didn't see anything missing or any missing colors.

**Comment by dolfinus** [comment]
Great, thank you. I've updated info on MediaWiki extension page about separated branch for older versions.
